const AppActionsConstants = {
  UPDATE_SEARCHPARAM: 'UPDATE_SEARCHPARAM',
  UPDATE_SEARCHFOR: 'UPDATE_SEARCHFOR',
  UPDATE_SEARCHREQ: 'UPDATE_SEARCHREQ',
  UPDATE_SEARCHUSERNAME: 'UPDATE_SEARCHUSERNAME',
  UPDATE_SEARCHUSERLOCATION: 'UPDATE_SEARCHUSERLOCATION',
};

export { AppActionsConstants}
