const RestProfileActionsConstants = {
  GET_GENERALDETAILES: 'GET_GENERALDETAILES',
  LOAD_GENERALDETAILES: 'LOAD_GENERALDETAILES',
  GET_REVIEWS: 'GET_REVIEWS',
  LOAD_REVIEWS: 'LOAD_REVIEWS',
  RESET_REVIEWS: 'RESET_REVIEWS',
  UPDATE_RESTPROF_ALERT: 'UPDATE_RESTPROF_ALERT',
};

export { RestProfileActionsConstants}
