const WriteReviewActionsConstants = {
  UPDATE_BATHROOMQUALITY: 'UPDATE_BATHROOMQUALITY',
  UPDATE_STAFFKINDNESS: 'UPDATE_STAFFKINDNESS',
  UPDATE_CLEANLINESS: 'UPDATE_CLEANLINESS',
  UPDATE_DRIVETHROUGH: 'UPDATE_DRIVETHROUGH',
  UPDATE_DELIVERYSPEED: 'UPDATE_DELIVERYSPEED',
  UPDATE_FOODQUALITY: 'UPDATE_FOODQUALITY',
  UPDATE_TITLE: 'UPDATE_TITLE',
  UPDATE_REVIEW: 'UPDATE_REVIEW',
  UPLOAD_PHOTOS: 'UPLOAD_PHOTOS',
  SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  SUBMISSION_SUCCESS: 'SUBMISSION_SUCCESS',
  UPDATE_ALLREVIEW: 'UPDATE_ALLREVIEW',
  GET_REVIEWINFO: 'GET_REVIEWINFO',
  UPDATE_REVIEWSTART:'UPDATE_REVIEWSTART',
};

export { WriteReviewActionsConstants}
