const LoginActionsConstants = {
  LOGIN: 'LOGIN',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  LOGIN_SUCCESS_ACTION: 'LOGIN_SUCCESS_ACTION',
  LOGIN_FAILED_ACTION: 'LOGIN_FAILED_ACTION',
  INIT_ERROR_ACTION : 'INIT_ERROR_ACTION'
};

export { LoginActionsConstants}
