const SignUpActionsConstants = {
  CREATE_USER: 'CREATE_USER',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  UPDATE_FIRSTNAME: 'UPDATE_FIRSTNAME',
  UPDATE_LASTNAME: 'UPDATE_LASTNAME',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  FIND_USERNAME: 'FIND_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  UPDATE_IMAGE: 'UPDATE_IMAGE',
  UPDATE_USEREXISTS: 'UPDATE_USEREXISTS',
};

export { SignUpActionsConstants};
