const RestResultsActionsConstants = {
  LOAD_REST_RESULTS: 'LOAD_REST_RESULTS',
  UPDATE_ALERT: 'UPDATE_ALERT',
  RESET_RESTAURANTS: 'RESET_RESTAURANTS',
  UPDATE_MOREREQ: 'UPDATE_MOREREQ',
  UPDATE_NORESULTS: 'UPDATE_NORESULTS',
};

export { RestResultsActionsConstants}
