const ReviewsSortActionsConstants = {
  UPDATE_SORTDATE: 'UPDATE_SORTDATE',
  UPDATE_FILTERDATE: 'UPDATE_FILTERDATE',
  UPDATE_SORTTOPIC: 'UPDATE_SORTTOPIC',
  UPDATE_FILTERTOPIC: 'UPDATE_FILTERTOPIC',
  REVIEWS_SORT_UPDATED: 'REVIEWS_SORT_UPDATED'
};

export { ReviewsSortActionsConstants}
