const UserProfileActionsConstants = {
  UPDATE_USERINFO: 'UPDATE_USERINFO',
  GET_USERINFO: 'GET_USERINFO',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_FIRSTNAME: 'UPDATE_FIRSTNAME',
  UPDATE_LASTNAME: 'UPDATE_LASTNAME',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  UPDATE_IMAGE: 'UPDATE_IMAGE',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  UPDATE_FAILED: 'UPDATE_FAILED',
  INIT_MESSAGE: 'INIT_MESSAGE',
  DELETE_REVIEW: 'DELETE_REVIEW',
  FIND_USERNAME: 'FIND_USERNAME',
  UPDATE_USEREXISTS: 'UPDATE_USEREXISTS',
  GET_USER_REVIEWS: 'GET_USER_REVIEWS',
  LOAD_USER_REVIEWS: 'LOAD_USER_REVIEWS',
  RESET_USER_REVIEWS: 'RESET_USER_REVIEWS',
};

export { UserProfileActionsConstants};
